Use source code version for now to avoid using different version depending on repository setting.

diff --git a/usr/share/usability-misc/build-dist-installer-cli b/usr/share/usability-misc/build-dist-installer-cli
--- a/usr/share/usability-misc/build-dist-installer-cli
+++ b/usr/share/usability-misc/build-dist-installer-cli
@@ -25,19 +25,25 @@ template="${toplevel}/usr/bin/dist-installer-cli"
 
 ## debian/control 'Builds-Depends: helper-scripts' is not easily possible,
 ## because then the build chroot would also need helper-scripts being installed.
-if test -d /usr/libexec/helper-scripts/ ; then
-  ## System version.
-  ## Stable. Or not. Depending on repository setting stable, stable-proposed-updates, testers, or developers.
-  helper_path="/usr/libexec/helper-scripts/"
-elif test -d "../helper-scripts/usr/libexec/helper-scripts/" ; then
-  ## derivative-maker source code version.
-  helper_path="../helper-scripts/usr/libexec/helper-scripts/"
-else
-  echo "$0: ERROR: helper_path neither available in
-- /usr/libexec/helper-scripts/
-nor in
-../helper-scripts/usr/libexec/helper-scripts/" >&2
-  exit 1
+# if test -d /usr/libexec/helper-scripts/ ; then
+#   ## System version.
+#   ## Stable. Or not. Depending on repository setting stable, stable-proposed-updates, testers, or developers.
+#   helper_path="/usr/libexec/helper-scripts/"
+# elif test -d "../helper-scripts/usr/libexec/helper-scripts/" ; then
+#   ## derivative-maker source code version.
+#   helper_path="../helper-scripts/usr/libexec/helper-scripts/"
+# else
+#   echo "$0: ERROR: helper_path neither available in
+# - /usr/libexec/helper-scripts/
+# nor in
+# ../helper-scripts/usr/libexec/helper-scripts/" >&2
+#   exit 1
+# fi
+
+## Use source code version for now to avoid using different version depending on repository setting.
+helper_path="../helper-scripts/usr/libexec/helper-scripts/"
+if ! test -d "$helper_path" ; then
+  echo "$0: ERROR: directory helper_path '$helper_path' does not exist!" >&2
 fi
 
 cp "${template}" "${target}"
