build

diff --git a/usr/share/usability-misc/dist-installer-cli-standalone b/usr/share/usability-misc/dist-installer-cli-standalone
--- a/usr/share/usability-misc/dist-installer-cli-standalone
+++ b/usr/share/usability-misc/dist-installer-cli-standalone
@@ -554,15 +554,15 @@ get_installer_package_version() {
     return 0
   fi
   ## Do not use commit-hash replace-me as search string to avoid replacement script replacing this.
-  if ! printf '%s' "${version}" | grep --quiet --fixed-strings "replace-me" ; then
+  if ! printf '%s' "${version}" | grep --quiet --fixed-strings -- "replace-me" ; then
     true "INFO: version variable does not match replace-me string."
     return 0
   fi
-  if ! printf '%s' "${0}" | grep --quiet '^/usr/bin' ; then
+  if ! printf '%s' "${0}" | grep --quiet -- '^/usr/bin' ; then
     true "INFO: variable 0 does not match ^/usr/bin string. This means not for example /usr/bin/dist-installer-cli. So not packages dist-installer-cli version."
     return 0
   fi
-  if ! printf '%s' "${me}" | grep --quiet --fixed-strings "installer-cli" ; then
+  if ! printf '%s' "${me}" | grep --quiet --fixed-strings -- "installer-cli" ; then
     true "INFO: program name variable does not match installer-cli string."
     return 0
   fi
@@ -1104,7 +1104,7 @@ secure_boot_test() {
   local mokutil_output_sb_state
   secure_boot_dkms_key_enrolled=""
   if mokutil_output_sb_state=$(root_cmd mokutil --sb-state 2>&1) ; then
-    if printf '%s' "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings enabled ; then
+    if printf '%s' "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings -- "enabled" ; then
       secure_boot_status_pretty="'enabled' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
       secure_boot_status_short=true
       ## sudo mokutil --test-key /var/lib/dkms/mok.pub
@@ -1114,10 +1114,10 @@ secure_boot_test() {
       ## Redirection '2>&1' not necessary yet but that could be considered a minor bug in mokutil to write to stdout instead
       ## of writing to stderr.
       secure_boot_mokutil_dkms_test_key="$(root_cmd mokutil --test-key "/var/lib/dkms/mok.pub" 2>&1)" || true
-      if printf '%s' "$secure_boot_mokutil_dkms_test_key" | grep --quiet --ignore-case --fixed-strings "already enrolled" ; then
+      if printf '%s' "$secure_boot_mokutil_dkms_test_key" | grep --quiet --ignore-case --fixed-strings -- "already enrolled" ; then
         secure_boot_dkms_key_enrolled=true
       fi
-    elif printf '%s' "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings disabled ; then
+    elif printf '%s' "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings -- "disabled" ; then
       secure_boot_status_short=false
       secure_boot_status_pretty="'disabled' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
     else
@@ -1296,10 +1296,10 @@ update_sources() {
 
   if update_output=$(root_cmd_loglevel=notice root_cmd "${update_cmd[@]}" 2>&1 | "${console_write_command[@]}") ; then
     true "INFO: Exit code is zero but that does not guarantee in case of dnf that there is no error."
-    if printf '%s' "$update_output" | grep --quiet --ignore-case "Error:" ; then
+    if printf '%s' "$update_output" | grep --quiet --ignore-case -- "Error:" ; then
       log error "${underline}Package List Update:${nounderline} Exit code was 0 but 'Error:' found in output."
-      if printf '%s' "$update_output" | grep --quiet --ignore-case "GPG signature verification error: Signing key not"; then
-        log warn "${underline}Package List Update:${nounderline} Signing key not found. Skipping due to 'rpm --import' failing to import keys but '--assumeyes' being used will import keys"
+      if printf '%s' "$update_output" | grep --quiet --ignore-case -- "GPG signature verification error: Signing key not"; then
+        log warn "${underline}Package List Update:${nounderline} Signing key not found. Skipping due to 'rpm --import' failing to import keys, but '--assumeyes' being used will import keys."
         return 0
       fi
       update_sources_error
@@ -1343,7 +1343,7 @@ check_upgrades_simulation() {
     && upgrade_simulate_cmd+=( "${#install_pkg_fasttrack_extra_args_maybe[@]}" )
   if upgrade_simulate_output=$(root_cmd_loglevel=notice root_cmd "${upgrade_simulate_cmd[@]}" 2>&1 | "${console_write_command[@]}") ; then
     true "INFO: Exit code is zero but that does not guarantee in case of dnf that there is no error."
-    if printf '%s' "$upgrade_simulate_output" | grep --quiet --ignore-case "Error:" ; then
+    if printf '%s' "$upgrade_simulate_output" | grep --quiet --ignore-case -- "Error:" ; then
       log error "${underline}Package Upgrade Simulation:${nounderline} Exit code was 0 but 'Error:' found in output."
       upgrade_simulate_sources_error
     fi
@@ -1440,7 +1440,7 @@ install_pkg() {
     log info "special_args: '${special_args[*]}'"
 
     if ! root_cmd "${pkg_mngr_install[@]}" "${special_args[@]}" "${pkg_not_installed[@]}"; then
-      if printf '%s' "${pkg_not_installed[*]}" | grep --quiet --ignore-case virtualbox ; then
+      if printf '%s' "${pkg_not_installed[*]}" | grep --quiet --ignore-case -- "virtualbox" ; then
         virtualbox_installation_failure_debug
       fi
       die 1 "${underline}Package Installation:${nounderline} Failed to install package: '${pkg_not_installed[*]}'"
@@ -1500,9 +1500,9 @@ check_vm_running_virtualbox() {
   vm="${1}"
   ## Paused state should be considered as running. Instead of grepping
   ## possible states, grep VM from list of running VMs.
-  # vboxmanage list runningvms | grep -q "^\"${vm}\" "
+  # vboxmanage list runningvms | grep -q -- "^\"${vm}\" "
   if run_as_target_user "${vboxmanage_locale_english[@]}" showvminfo "${vm}" 2>&1 | \
-    grep -qE "^State:[[:space:]]+(running|paused)"
+    grep -qE -- "^State:[[:space:]]+(running|paused)"
   then
     log error "Cannot proceed. You have the following VM running: ${vm}"
     die 1 "${underline}VM Running Check:${nounderline} Please turn it off before re-running this installer."
@@ -1866,9 +1866,9 @@ extract_vm_name_from_virtualbox_ova() {
   local output="$1"
   local system_number="$2"
   local a b c d
-  a=$(printf '%s' "$output" | grep --max-count=1 --after-context=4 "Virtual system $system_number:")
-  b=$(printf '%s' "$a" | grep "Suggested VM name")
-  c=$(printf '%s' "$b" | grep -oP '"\K[^"]+')
+  a=$(printf '%s' "$output" | grep --max-count=1 --after-context=4 -- "Virtual system $system_number:")
+  b=$(printf '%s' "$a" | grep -- "Suggested VM name")
+  c=$(printf '%s' "$b" | grep -oP -- '"\K[^"]+')
   ## Take first word only because VirtualBox would suggest name "Whonix-Gateway-Xfce 1" in case,
   ## a VM "Whonix-Gateway-Xfce" is already registered in VirtualBox.
   d=$(printf '%s' "$c" | awk '{print $1}')
@@ -2022,7 +2022,7 @@ start_virtualbox_vm() {
 
 
 start_virtualbox_gui() {
-  if pgrep 'VirtualBox$' >/dev/null ; then
+  if pgrep -- 'VirtualBox$' >/dev/null ; then
     log notice "VirtualBox Manager Startup Result: Not starting duplicate VirtualBox GUI because already running."
     return 0
   fi
@@ -2059,7 +2059,7 @@ get_pattern_sources_debian() {
 
   file="${1}"
   pattern="${2}"
-  grep -v "^\s*#" -- "${file}" | grep -q -E "${pattern}" || return 1
+  grep -v "^\s*#" -- "${file}" | grep -q -E -- "${pattern}" || return 1
 }
 
 write_sources_debian() {
@@ -2212,7 +2212,7 @@ add_user_to_vbox_group() {
   local id_of_user
 
   id_of_user="$(id --name --user)" || die 1 "${underline}Linux user ID check:${nounderline} Failed to run: 'id --name --user'"
-  if id -nG "${id_of_user}" | grep -qw "${virtualbox_linux_user_group}\$"; then
+  if id -nG "${id_of_user}" | grep -qw -- "${virtualbox_linux_user_group}\$"; then
     log info "Linux Group Configuration: Account '${id_of_user}' is already a member of the Linux group 'vboxusers'."
     return 0
   fi
@@ -2315,7 +2315,7 @@ install_repositories_for_virtualbox_on_debian() {
   distro_codename_real=$(lsb_release --short --codename)
   distro_codename_common_use="${distro_codename_real}"
   if [ "${ubuntu_derivative_detected}" = "1" ]; then
-    if grep -q "^UBUNTU_CODENAME=\S\+=" -- /etc/os-release; then
+    if grep -q -- "^UBUNTU_CODENAME=\S\+=" -- /etc/os-release; then
       distro_codename_ubuntu="$(awk -F'=' '/^UBUNTU_CODENAME=/{print $2}' /etc/os-release)"
     else
       distro_codename_ubuntu="noble"
@@ -2512,7 +2512,7 @@ install_repositories_for_virtualbox_on_debian() {
     else
       kali_domain_debsource="${kali_clearnet}"
       oracle_domain_debsource="${oracle_clearnet}"
-      log warn "Fallback Fasttrack repository to clearnet"
+      log warn "Fallback FastTrack repository to clearnet."
       fasttrack_domain_debsource="${fasttrack_clearnet}"
     fi
     kicksecure_domain_debsource="${kicksecure_onion}"
@@ -2579,10 +2579,10 @@ install_repositories_for_virtualbox_on_debian() {
 
 install_oracle_repository_fedora() {
   oracle_found=""
-  if dnf repolist --all virtualbox | grep -q "."; then
+  if dnf repolist --all virtualbox | grep -q -- "."; then
     oracle_found="1"
   fi
-  if dnf repolist --disabled virtualbox | grep -q "."; then
+  if dnf repolist --disabled virtualbox | grep -q -- "."; then
     dnf config-manager --set-enabled virtualbox
   fi
   if [ "${oracle_found}" = "1" ]; then
@@ -2802,7 +2802,7 @@ install_virtualbox_fedora() {
 #     ## --cacheonly does not work.
 #     ## Maybe dnf would need to be run with root_cmd.
 #     virtualbox_version=$(dnf search "VirtualBox-*")
-#     virtualbox_version=$(printf '%s' "$virtualbox_version" | grep "^VirtualBox-[[:digit:]]\{1,2\}\.[[:digit:]]\{1,2\}\.")
+#     virtualbox_version=$(printf '%s' "$virtualbox_version" | grep -- "^VirtualBox-[[:digit:]]\{1,2\}\.[[:digit:]]\{1,2\}\.")
 #     virtualbox_version=$(printf '%s' "$virtualbox_version" | tail -1)
 #     virtualbox_version=$(printf '%s' "$virtualbox_version" | cut -d " " -f1)
 #     virtualbox_version=$(printf '%s' "$virtualbox_version" | cut -d "-" -f2-)
@@ -2895,7 +2895,7 @@ install_virtualbox_debian_common_begin() {
     done
   fi
   if has vboxmanage && ! dpkg --search "$(command -v vboxmanage)"; then
-    die 109 "Found Oracle VirtualBox installed from tarball/source, using a package manager can conflict with yourinstalled program. Uninstall VirtualBox first and then rerun this script. Use the option '--oracle-repo' if you want to keep close to upstream releases."
+    die 109 "Found Oracle VirtualBox installed from tarball/source. Using a package manager can conflict with your already manually installed VirtualBox. Uninstall VirtualBox first and then rerun this script. Use the option '--oracle-repo' if you want to install from the Oracle repository."
   fi
 
   install_repositories_for_virtualbox_on_debian
@@ -3571,7 +3571,7 @@ get_virtualization() {
 
   ## Check if virtualization is enabled.
   ## Check CPU flags for capability
-  virt_flag="$(root_cmd grep -m1 -w '^flags[[:blank:]]*:' /proc/cpuinfo | grep -wo -E '(vmx|svm)' || true)"
+  virt_flag="$(root_cmd grep -m1 -w -- '^flags[[:blank:]]*:' /proc/cpuinfo | grep -wo -E -- '(vmx|svm)' || true)"
 
   case "${virt_flag:=none}" in
     vmx) brand=intel;;
@@ -3673,8 +3673,8 @@ get_virtualization() {
   }
 
   ## Check CPU flags for capability
-  virt=$(root_cmd grep -m1 -w '^flags[[:blank:]]*:' /proc/cpuinfo |
-         grep -wo -E '(vmx|svm)') || true
+  virt=$(root_cmd grep -m1 -w -- '^flags[[:blank:]]*:' /proc/cpuinfo |
+         grep -wo -E -- '(vmx|svm)') || true
   if [ -z "${virt}" ]; then
     log error "Your CPU does not support Virtualization."
     verdict 1
