build

diff --git a/usr/share/usability-misc/dist-installer-cli-standalone b/usr/share/usability-misc/dist-installer-cli-standalone
--- a/usr/share/usability-misc/dist-installer-cli-standalone
+++ b/usr/share/usability-misc/dist-installer-cli-standalone
@@ -595,15 +595,15 @@ get_installer_package_version() {
     return 0
   fi
   ## Do not use commit-hash replace-me as search string to avoid replacement script replacing this.
-  if ! printf '%s' "${version}" | grep --quiet --fixed-strings -- "replace-me" ; then
+  if ! printf '%s' "${version}" | grep --fixed-strings -- "replace-me" >/dev/null ; then
     true "INFO: version variable does not match replace-me string."
     return 0
   fi
-  if ! printf '%s' "${0}" | grep --quiet -- '^/usr/bin' ; then
+  if ! printf '%s' "${0}" | grep -- '^/usr/bin' >/dev/null ; then
     true "INFO: variable 0 does not match ^/usr/bin string. This means not for example /usr/bin/dist-installer-cli. So not packages dist-installer-cli version."
     return 0
   fi
-  if ! printf '%s' "${me}" | grep --quiet --fixed-strings -- "installer-cli" ; then
+  if ! printf '%s' "${me}" | grep --fixed-strings -- "installer-cli" >/dev/null ; then
     true "INFO: program name variable does not match installer-cli string."
     return 0
   fi
@@ -1164,7 +1164,7 @@ secure_boot_test() {
   local mokutil_output_sb_state
   secure_boot_dkms_key_enrolled=""
   if mokutil_output_sb_state=$(root_cmd mokutil --sb-state 2>&1) ; then
-    if printf '%s' "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings -- "enabled" ; then
+    if printf '%s' "$mokutil_output_sb_state" | grep --ignore-case --fixed-strings -- "enabled" >/dev/null; then
       secure_boot_status_pretty="'enabled' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
       secure_boot_status_short=true
       ## sudo mokutil --test-key /var/lib/dkms/mok.pub
@@ -1174,10 +1174,10 @@ secure_boot_test() {
       ## Redirection '2>&1' not necessary yet but that could be considered a minor bug in mokutil to write to stdout instead
       ## of writing to stderr.
       secure_boot_mokutil_dkms_test_key="$(root_cmd mokutil --test-key "/var/lib/dkms/mok.pub" 2>&1)" || true
-      if printf '%s' "$secure_boot_mokutil_dkms_test_key" | grep --quiet --ignore-case --fixed-strings -- "already enrolled" ; then
+      if printf '%s' "$secure_boot_mokutil_dkms_test_key" | grep --ignore-case --fixed-strings -- "already enrolled" >/dev/null ; then
         secure_boot_dkms_key_enrolled=true
       fi
-    elif printf '%s' "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings -- "disabled" ; then
+    elif printf '%s' "$mokutil_output_sb_state" | grep --ignore-case --fixed-strings -- "disabled" >/dev/null ; then
       secure_boot_status_short=false
       secure_boot_status_pretty="'disabled' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
     else
@@ -1356,9 +1356,9 @@ update_sources() {
 
   if update_output=$(root_cmd_loglevel=notice root_cmd "${update_cmd[@]}" 2>&1 | "${console_write_command[@]}") ; then
     true "INFO: Exit code is zero but that does not guarantee in case of dnf that there is no error."
-    if printf '%s' "$update_output" | grep --quiet --ignore-case -- "Error:" ; then
+    if printf '%s' "$update_output" | grep --ignore-case -- "Error:" >/dev/null ; then
       log error "${underline}Package List Update:${nounderline} Exit code was 0 but 'Error:' found in output."
-      if printf '%s' "$update_output" | grep --quiet --ignore-case -- "GPG signature verification error: Signing key not"; then
+      if printf '%s' "$update_output" | grep --ignore-case -- "GPG signature verification error: Signing key not" >/dev/null; then
         log warn "${underline}Package List Update:${nounderline} Signing key not found. Skipping due to 'rpm --import' failing to import keys, but '--assumeyes' being used will import keys."
         return 0
       fi
@@ -1402,7 +1402,7 @@ check_upgrades_simulation() {
     && upgrade_simulate_cmd+=( "${install_pkg_fasttrack_extra_args_maybe[@]}" )
   if upgrade_simulate_output=$(root_cmd_loglevel=notice root_cmd "${upgrade_simulate_cmd[@]}" 2>&1 | "${console_write_command[@]}") ; then
     true "INFO: Exit code is zero but that does not guarantee in case of dnf that there is no error."
-    if printf '%s' "$upgrade_simulate_output" | grep --quiet --ignore-case -- "Error:" ; then
+    if printf '%s' "$upgrade_simulate_output" | grep --ignore-case -- "Error:" >/dev/null ; then
       log error "${underline}Package Upgrade Simulation:${nounderline} Exit code was 0 but 'Error:' found in output."
       upgrade_simulate_sources_error
     fi
@@ -1502,7 +1502,7 @@ install_pkg() {
     log info "special_args: '${special_args[*]}'"
 
     if ! root_cmd "${pkg_mngr_install[@]}" "${special_args[@]}" "${pkg_not_installed[@]}"; then
-      if printf '%s' "${pkg_not_installed[*]}" | grep --quiet --ignore-case -- "virtualbox" ; then
+      if printf '%s' "${pkg_not_installed[*]}" | grep --ignore-case -- "virtualbox" >/dev/null; then
         virtualbox_installation_failure_debug
       fi
       die 1 "${underline}Package Installation:${nounderline} Failed to install package: '${pkg_not_installed[*]}'"
@@ -1562,9 +1562,9 @@ check_vm_running_virtualbox() {
   vm="${1}"
   ## Paused state should be considered as running. Instead of grepping
   ## possible states, grep VM from list of running VMs.
-  # vboxmanage list runningvms | grep -q -- "^\"${vm}\" "
+  # vboxmanage list runningvms | grep -- "^\"${vm}\" " >/dev/null
   if run_as_target_user "${vboxmanage_locale_english[@]}" showvminfo "${vm}" 2>&1 | \
-    grep -qE -- "^State:[[:space:]]+(running|paused)"
+    grep -E -- "^State:[[:space:]]+(running|paused)" >/dev/null
   then
     log error "Cannot proceed. You have the following VM running: ${vm}"
     die 1 "${underline}VM Running Check:${nounderline} Please turn it off before re-running this installer."
@@ -2126,7 +2126,7 @@ get_pattern_sources_debian() {
 
   file="${1}"
   pattern="${2}"
-  grep -v "^\s*#" -- "${file}" | grep -q -E -- "${pattern}" || return 1
+  grep -v "^\s*#" -- "${file}" | grep -E -- "${pattern}" >/dev/null || return 1
 }
 
 write_sources_debian() {
@@ -2296,7 +2296,7 @@ add_user_to_vbox_group() {
   local id_of_user
 
   id_of_user="$(id --name --user)" || die 1 "${underline}Linux user ID check:${nounderline} Failed to run: 'id --name --user'"
-  if id -nG "${id_of_user}" | grep -qw -- "${virtualbox_linux_user_group}\$"; then
+  if id -nG "${id_of_user}" | grep -w -- "${virtualbox_linux_user_group}\$" >/dev/null; then
     log info "Linux Group Configuration: Account '${id_of_user}' is already a member of the Linux group 'vboxusers'."
     return 0
   fi
@@ -2399,7 +2399,7 @@ install_repositories_for_virtualbox_on_debian() {
   distro_codename_real=$(lsb_release --short --codename)
   distro_codename_common_use="${distro_codename_real}"
   if [ "${ubuntu_derivative_detected}" = "1" ]; then
-    if grep -q -- "^UBUNTU_CODENAME=\S\+=" -- /etc/os-release; then
+    if grep --quiet -- "^UBUNTU_CODENAME=\S\+=" -- /etc/os-release; then
       distro_codename_ubuntu="$(awk -F'=' '/^UBUNTU_CODENAME=/{print $2}' /etc/os-release)"
     else
       distro_codename_ubuntu="noble"
@@ -2663,10 +2663,10 @@ install_repositories_for_virtualbox_on_debian() {
 
 install_oracle_repository_fedora() {
   oracle_found=""
-  if dnf repolist --all virtualbox | grep -q -- "."; then
+  if dnf repolist --all virtualbox | grep -- "." >/dev/null; then
     oracle_found="1"
   fi
-  if dnf repolist --disabled virtualbox | grep -q -- "."; then
+  if dnf repolist --disabled virtualbox | grep -- "." >/dev/null; then
     dnf config-manager --set-enabled virtualbox
   fi
   if [ "${oracle_found}" = "1" ]; then
