build

diff --git a/usr/share/usability-misc/dist-installer-cli-standalone b/usr/share/usability-misc/dist-installer-cli-standalone
--- a/usr/share/usability-misc/dist-installer-cli-standalone
+++ b/usr/share/usability-misc/dist-installer-cli-standalone
@@ -1072,19 +1072,81 @@ nested_virtualization_test() {
 
 
 secure_boot_test() {
-  local mokutil_output
-  if mokutil_output=$(mokutil --sb-state 2>&1) ; then
-    if echo "$mokutil_output" | grep --quiet --ignore-case --fixed-strings enabled ; then
-      secure_boot_status="'enabled' (mokutil_output: '$mokutil_output')"
-    elif echo "$mokutil_output" | grep --quiet --ignore-case --fixed-strings disabled ; then
-      secure_boot_status="'disabled' (mokutil_output: '$mokutil_output')"
+  local mokutil_output_sb_state
+  secure_boot_dkms_key_enrolled=""
+  if mokutil_output_sb_state=$(root_cmd mokutil --sb-state 2>&1) ; then
+    if echo "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings enabled ; then
+      secure_boot_status_pretty="'enabled' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
+      secure_boot_status_short=true
+      ## sudo mokutil --test-key /var/lib/dkms/mok.pub
+      ## > /var/lib/dkms/mok.pub is already enrolled
+      ## > zsh: exit 1     sudo mokutil --test-key /var/lib/dkms/mok.pub#
+      ## Added "|| true" to handle the non-zero exit code.
+      ## Redirection '2>&1' not necessary yet but that could be considered a minor bug in mokutil to write to stdout instead
+      ## of writing to stderr.
+      secure_boot_mokutil_dkms_test_key="$(root_cmd mokutil --test-key "/var/lib/dkms/mok.pub" 2>&1)" || true
+      if echo "$secure_boot_mokutil_dkms_test_key" | grep --quiet --ignore-case --fixed-strings "already enrolled" ; then
+        secure_boot_dkms_key_enrolled=true
+      fi
+    elif echo "$mokutil_output_sb_state" | grep --quiet --ignore-case --fixed-strings disabled ; then
+      secure_boot_status_short=false
+      secure_boot_status_pretty="'disabled' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
     else
-      secure_boot_status="'unknown-please-report-this-minor-bug' (mokutil_output: '$mokutil_output')"
+      secure_boot_status_short=false
+      secure_boot_status_pretty="'unknown-please-report-this-minor-bug' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
     fi
   else
-    secure_boot_status="'disabled' (mokutil_output: '$mokutil_output')"
+    secure_boot_status_short=false
+    secure_boot_status_pretty="'disabled' (mokutil_output_sb_state: '$mokutil_output_sb_state')"
   fi
-  log info "Secure Boot Check Result: $secure_boot_status Ok."
+  log info "Secure Boot Check Result: $secure_boot_status_pretty Ok."
+}
+
+
+dkms_signing_key_enrollment() {
+  if [ ! "$secure_boot_status_short" = "true" ]; then
+    log info "${underline}Secure Boot DKMS Signing Key Enrollment Check Result:${nounderline} Secure Boot is disabled, therefore DKMS signing key enrollment is unnecessary, ok."
+    return 0
+  fi
+  if [ "$secure_boot_dkms_key_enrolled" = "true" ]; then
+    log info "${underline}Secure Boot DKMS Signing Key Enrollment Check Result:${nounderline} Secure Boot is enabled and DKMS signing key has already been enrolled, ok."
+    return 0
+  fi
+  if ! [ "${hypervisor}" = "virtualbox" ]; then
+    log info "${underline}Secure Boot DKMS Signing Key Enrollment Check Result:${nounderline} Secure Boot is enabled, but the DKMS signing key is not enrolled. This is however unnecessary for hypervisor '${hypervisor}'."
+    return 0
+  fi
+
+  log notice "secure_boot_mokutil_dkms_test_key: '$secure_boot_mokutil_dkms_test_key'"
+
+  ## Not simple to automate, because it requires a password prompt.
+  ## https://git.launchpad.net/~ubuntu-core-dev/shim/+git/shim-signed/tree/update-secureboot-policy
+  #root_cmd mokutil --import /var/lib/dkms/mok.pub
+  ##
+  ## sudo mokutil --import /var/lib/dkms/mok.pub
+  ## if already enrolled:
+  ## > SKIP: /var/lib/dkms/mok.pub is already enrolled
+  ##
+  ## sudo mokutil --test-key /var/lib/dkms/mok.pub
+  ## > /var/lib/dkms/mok.pub is not enrolled
+  ## With exit code 0.
+  ##
+  ## sudo mokutil --root-pw --import /var/lib/dkms/mok.pub
+  ## This can fail if the root account is locked / has no password such as in Kicksecure.
+  ## > Failed to get root password hash
+  ##
+  ## This is a Debian DKMS issue:
+  ## - dkms Debian: enroll DKMS signing key / automate running "sudo mokutil --import /var/lib/dkms/mok.pub"
+  ##   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1076269
+  ## - shim-signed Debian: please update update-secureboot-policy / add '--new-key' option
+  ##   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1076278
+  ## - dkms upstream: automate running "`sudo mokutil --import /var/lib/dkms/mok.pub`"
+  ##   https://github.com/dell/dkms/issues/429
+
+  die 1 "${underline}Secure Boot DKMS Signing Key Enrollment Check Result:${nounderline}
+
+Secure Boot is enabled, but the DKMS signing key is not enrolled. For further information, see:
+https://www.kicksecure.com/wiki/Secure_Boot"
 }
 
 
@@ -1614,7 +1676,7 @@ check_guest_boot(){
     ## Kernel modules have not been load.
     user_warned_potential_startup_issue=true
     log warn "Debugging information:
-Secure Boot Status: '$secure_boot_status'
+Secure Boot Status: '$secure_boot_status_pretty'
 Kernel module has been load: '$kernel_module_has_been_load'
 Kernel module can be load: '$kernel_modules_can_be_load' (modules can be load. (sysctl kernel.modules_disabled=0 is set.)
 Only signed kernel modules can be load: '$modules_signed_only'
@@ -4233,6 +4295,7 @@ run_installer(){
   kernel_modules_check
   nested_virtualization_test
   secure_boot_test
+  dkms_signing_key_enrollment
   kernel_modules_load
   kernel_modules_signed_only
   get_transfer_cmd
