improve

diff --git a/usr/libexec/usability-misc/check-user-slice-on-shutdown b/usr/libexec/usability-misc/check-user-slice-on-shutdown
--- a/usr/libexec/usability-misc/check-user-slice-on-shutdown
+++ b/usr/libexec/usability-misc/check-user-slice-on-shutdown
@@ -8,18 +8,22 @@ set -o nounset
 set -o errtrace
 set -o pipefail
 
+source /usr/libexec/helper-scripts/wc-test.sh
 source /usr/libexec/helper-scripts/light_sleep.bsh
+
+printf '%s\n' "$0: INFO: Start."
 
 counter=0
 while (( counter < 10 )); do
   light_sleep 1
-  systemd_cgls_output="$(systemd-cgls --unit user.slice)"
+  systemd_cgls_output="$(systemd-cgls --no-pager --unit user.slice)"
   if [ "$(wc -l <<< "$systemd_cgls_output")" == '1' ]; then
+    printf '%s\n' "$0: INFO: End. OK."
     exit 0
   fi
-  printf '%s\n' "WARNING: user.slice is not empty yet. Contents:"
-  printf '%s\n' "$systemd_cgls_output"
+  printf '%s\n' "$0: WARNING: user.slice is not empty yet. Contents:" >&2
+  printf '%s\n' "$systemd_cgls_output" >&2
 done
 
-printf '%s\n' "ERROR: user.slice not empty after 10 seconds!"
+printf '%s\n' "$0: ERROR: user.slice not empty after 10 seconds!" >&2
 exit 1
