Minor fixes in usability-misc.postinst, add shim-signed MOK key setup to postinst

diff --git a/debian/usability-misc.postinst b/debian/usability-misc.postinst
--- a/debian/usability-misc.postinst
+++ b/debian/usability-misc.postinst
@@ -10,7 +10,7 @@ fi
 set -e
 
 bisq_desktop_directories_workaround() {
-   if [ -f "/var/lib/usability-misc/do_once/${FUNCNAME}_version_1" ]; then
+   if [ -f "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1" ]; then
       return 0
    fi
 
@@ -18,11 +18,11 @@ bisq_desktop_directories_workaround() {
    mkdir -p /usr/share/desktop-directories
 
    mkdir -p "/var/lib/usability-misc/do_once"
-   touch "/var/lib/usability-misc/do_once/${FUNCNAME}_version_1"
+   touch "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1"
 }
 
 systemd_journald_audit_transport_enable() {
-   if [ -f "/var/lib/usability-misc/do_once/${FUNCNAME}_version_1" ]; then
+   if [ -f "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1" ]; then
       return 0
    fi
 
@@ -34,11 +34,11 @@ systemd_journald_audit_transport_enable() {
    deb-systemd-helper enable systemd-journald-audit.socket
 
    mkdir -p "/var/lib/usability-misc/do_once"
-   touch "/var/lib/usability-misc/do_once/${FUNCNAME}_version_1"
+   touch "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1"
 }
 
 generate_grub_keyboard_layouts_maybe() {
-   if [ -f "/var/lib/usability-misc/do_once/${FUNCNAME}_version_1" ]; then
+   if [ -f "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1" ]; then
       return 0
    fi
 
@@ -75,12 +75,74 @@ generate_grub_keyboard_layouts_maybe() {
    printf '%s\n' "INFO: Command 'set-grub-keymap --build-all' success."
 
    mkdir -p "/var/lib/usability-misc/do_once"
-   touch "/var/lib/usability-misc/do_once/${FUNCNAME}_version_1"
+   touch "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1"
+}
+
+shim_signed_mok_setup() {
+   if [ -f "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1" ]; then
+      return 0
+   fi
+
+   local dkms_mok_dir dkms_mok_public_file dkms_mok_private_file \
+      shim_mok_dir shim_mok_public_file shim_mok_private_file \
+      mok_keys_present third_party_kernel_module_warning
+
+   true "INFO: Setting up MOK secure boot keys if necessary..."
+
+   dkms_mok_dir='/var/lib/dkms'
+   dkms_mok_public_file="${dkms_mok_dir}/mok.pub"
+   dkms_mok_private_file="${dkms_mok_dir}/mok.key"
+   shim_mok_dir='/var/lib/shim-signed/mok'
+   shim_mok_public_file="${shim_mok_dir}/MOK.der"
+   shim_mok_private_file="${shim_mok_dir}/MOK.priv"
+   mok_keys_present='n'
+   third_party_kernel_module_warning="Third-party kernel modules and \
+applications that depend on them may not function if Secure Boot is enabled."
+
+   if ! [ -f "${dkms_mok_public_file}" ] \
+      || ! [ -f "${dkms_mok_private_file}" ]; then
+      if dkms generate_mok; then
+         mok_keys_present='y'
+      fi
+   else
+      mok_keys_present='y'
+   fi
+
+   if [ "${mok_keys_present}" != 'y' ]; then
+      printf '%s\n' "WARNING: '${dkms_mok_public_file}' and/or \
+'${dkms_mok_private_file}' do not exist, and DKMS errored out while trying \
+to generate them! ${third_party_kernel_module_warning}"
+      return
+   fi
+
+   if ! mkdir -p "${shim_mok_dir}"; then
+      printf '%s\n' "WARNING: Unable to create directory '${shim_mok_dir}'! \
+${third_party_kernel_module_warning}"
+      return
+   fi
+
+   if ! ln -s "${dkms_mok_public_file}" "${shim_mok_public_file}"; then
+      printf '%s\n' "WARNING: Unable to create symlink from \
+'${dkms_mok_public_file}' to '${shim_mok_public_file}'! \
+${third_party_kernel_module_warning}"
+      return
+   fi
+   if ! ln -s "${dkms_mok_private_file}" "${shim_mok_private_file}" ; then
+      printf '%s\n' "WARNING: Unable to create symlink from \
+'${dkms_mok_private_file}' to '${shim_mok_private_file}'! \
+${third_party_kernel_module_warning}"
+      return
+   fi
+
+   true "INFO: Done setting up MOK secure boot keys if necessary."
+
+   mkdir -p "/var/lib/usability-misc/do_once"
+   touch "/var/lib/usability-misc/do_once/${FUNCNAME[0]}_version_1"
 }
 
 true "
 #####################################################################
-## INFO: BEGIN: $DPKG_MAINTSCRIPT_PACKAGE $DPKG_MAINTSCRIPT_NAME $@
+## INFO: BEGIN: $DPKG_MAINTSCRIPT_PACKAGE $DPKG_MAINTSCRIPT_NAME $*
 #####################################################################
 "
 
@@ -102,6 +164,7 @@ esac
 
 bisq_desktop_directories_workaround
 systemd_journald_audit_transport_enable
+shim_signed_mok_setup
 
 if [ -d /run/systemd/system ] ; then
         systemd-tmpfiles --create /usr/lib/tmpfiles.d/50_openvpn_unpriv.conf >/dev/null || true
@@ -132,7 +195,7 @@ true "INFO: Done with debhelper."
 
 true "
 #####################################################################
-## INFO: END  : $DPKG_MAINTSCRIPT_PACKAGE $DPKG_MAINTSCRIPT_NAME $@
+## INFO: END  : $DPKG_MAINTSCRIPT_PACKAGE $DPKG_MAINTSCRIPT_NAME $*
 #####################################################################
 "
 
