set download directory via command-line option let the user choose the directory where files will be saved to.

diff --git a/usr/bin/installer-dist b/usr/bin/installer-dist
--- a/usr/bin/installer-dist
+++ b/usr/bin/installer-dist
@@ -713,7 +713,7 @@ import_virtualbox(){
   test "${guest}" = "whonix" && vbox_arg="${vbox_arg} --vsys 1 --eula accept"
   ## import virtualbox image
   vboxmanage import \
-    "${curl_opt_save_dir}/${guest_file}.${guest_file_ext}" ${vbox_arg}
+    "${directory_prefix}/${guest_file}.${guest_file_ext}" ${vbox_arg}
 }
 
 
@@ -804,7 +804,7 @@ get_system_stat(){
     log warn "You may encounter problems using a desktop environment."
   fi
 
-  free_space="$(df --output=avail -BG . | awk '/G$/{print substr($1, 1, length($1)-1)}')"
+  free_space="$(df --output=avail -BG ${directory_prefix} | awk '/G$/{print substr($1, 1, length($1)-1)}')"
   if [ "${free_space}" -lt 10 ]; then
     log error "You need at least 10G of available space, you only have ${free_space}G."
     return 1
@@ -941,15 +941,15 @@ get_version(){
 
 
 download_files(){
-  download_dir="${1:?}"
-  download_flag="${download_dir}/${guest_file}.${guest_file_ext}.flag"
+  download_flag="${directory_prefix}/${guest_file}.${guest_file_ext}.flag"
   if test -f "${download_flag}"; then
     log notice "Skipping download because flag exists: ${download_flag}."
     return 0
   fi
 
   log_elapsed_time
-  curl_full_download="curl --fail --show-error --location --create-dirs --output-dir ${download_dir} ${curl_opt_ssl:-} ${curl_proxy:-} $(get_curl_proxy_cred) --remote-name "
+  mkdir "${directory_prefix}"
+  curl_full_download="curl --fail --show-error --location --output-dir ${directory_prefix} ${curl_opt_ssl:-} ${curl_proxy:-} $(get_curl_proxy_cred) --remote-name "
 
   log notice "Downloading ${guest_file}.${guest_file_ext}."
   log_and_run "${curl_full_download} ${url_guest_file}.${guest_file_ext}" ||
@@ -1231,9 +1231,9 @@ main(){
   url_domain="${url_domain}/${guest_version:?}"
   guest_file="${guest_pretty}-${interface_all_caps}-${guest_version}"
   url_guest_file="${url_domain}/${guest_file}"
-  curl_opt_save_dir="${HOME}/installer-dist-download"
+  directory_prefix="${HOME}/installer-dist-download"
 
-  download_files "${curl_opt_save_dir}" || die 1 "Failed to download files."
+  download_files || die 1 "Failed to download files."
 
   if test "${dry_run}" = "1"; then
     log info "Ending run before doing integrity checks because dry_run is set."
@@ -1241,13 +1241,13 @@ main(){
   fi
 
   log notice "Signify signature:\n${signify_key}"
-  log notice "Verifying file: ${curl_opt_save_dir}/${guest_file}.sha512sums."
+  log notice "Verifying file: ${directory_prefix}/${guest_file}.sha512sums."
   echo "${signify_key}" | signify -V -p - \
-   -m "${curl_opt_save_dir}/${guest_file}.sha512sums" ||
+   -m "${directory_prefix}/${guest_file}.sha512sums" ||
     die 1 "Failed to verify signature."
 
-  log notice "Checking SHA512 checksum: ${curl_opt_save_dir}/${guest_file}.${guest_file_ext}"
-  ${checkhash} "${curl_opt_save_dir}/${guest_file}.sha512sums" ||
+  log notice "Checking SHA512 checksum: ${directory_prefix}/${guest_file}.${guest_file_ext}"
+  ${checkhash} "${directory_prefix}/${guest_file}.sha512sums" ||
     die 1 "Failed hash checking."
 
   ${import_guest}
@@ -1276,6 +1276,11 @@ usage(){
  -V, --version       Print script version.
  -h, --help          Print this help message.
 Developer options:
+ -P, --directory-prefix
+                     Set directory prefix to save files to. If you change this
+                       directory, but the previously downloaded files are not
+                       changed to the new directory, the download will be done
+                       again. \$HOME/installer-dist-download (default)
  -n, --non-interactive
                      Set non-interactive mode, license will be accepted.
  -d, --dry-run       Fake run, log commands to info level without executing.
@@ -1293,8 +1298,10 @@ File name:
 ## set default values of variables
 set_default(){
   arg_saved=""
-  guest=""
+  directory_prefix=""
+  set_arg directory_prefix "${HOME}/installer-dist-download"
   guest_version_user=""
+  guest=""
   set_arg guest whonix
   hypervisor=""
   set_arg hypervisor virtualbox
@@ -1339,6 +1346,9 @@ parse_opt(){
     begin_optparse "${1:-}" "${2:-}" || break
     # shellcheck disable=SC2034
     case "${opt}" in
+      P|directory-prefix)
+        get_arg directory_prefix
+        ;;
       o|onion)
         set_arg onion 1
         ;;
@@ -1388,6 +1398,16 @@ parse_opt(){
   range_arg guest whonix kicksecure
   range_arg interface cli xfce
   range_arg hypervisor kvm virtualbox
+
+  if ! test -d "${directory_prefix}"; then
+    die 1 "Directory doesn't exist: '${directory_prefix}'"
+  fi
+  if ! test -w "${directory_prefix}"; then
+    die 1 "Directory isn't writable: '${directory_prefix}'"
+  fi
+  if ! test -r "${directory_prefix}"; then
+    die 1 "Directory isn't readable: '${directory_prefix}'"
+  fi
 
   case "${dev:-}" in
     getopt)
