better logging xtrace for bash and fix mint

diff --git a/usr/bin/installer-dist b/usr/bin/installer-dist
--- a/usr/bin/installer-dist
+++ b/usr/bin/installer-dist
@@ -542,22 +542,29 @@ end_exit(){
 
 ## Handle exit trap with line it failed and its exit code.
 handle_exit(){
+  true "BEGIN handle_exit() with args: $*"
   last_exit="${1}"
   line_number="${2:-0}"
   log_time
   ## Exit without errors.
   test "${last_exit}" = "0" && end_exit
   ## Exit with errors.
+  log error "Current script: ${0}"
+  if test -n "${BASH_COMMAND:-}"; then
+    log error "Function executed: ${FUNCNAME[1]}"
+    log error "Command executed: ${BASH_COMMAND}"
+  fi
   ## some shells have a bug that displays line 1 as LINENO
   if test "${line_number}" -gt 2; then
     log bug "At line: ${line_number}."
-    pr -tn "${0}" | tail -n+$((line_number - 3)) | head -n7
+    ## ideas from https://unix.stackexchange.com/questions/39623/trap-err-and-echoing-the-error-line
+    # pr -tn "${0}" | tail -n+$((line_number - 3)) | head -n7
+    awk 'NR>L-4 && NR<L+4 { printf " %-5d%3s %s\n",NR,(NR==L?">>>":""),$0 }' L="${line_number}" "${0}" >&2
   else
     if [ "${last_exit}" -gt 128 ] && [ "${last_exit}" -lt 193 ]; then
-      if has bc; then
-        signal_caught="$(kill -l "$(echo "${last_exit}"-128 | bc)")"
-        log error "Received ${signal_caught} signal."
-      fi
+      signal_code=$((last_exit-128))
+      signal_caught="$(kill -l "${signal_code}")"
+      log error "Received ${signal_caught} signal."
     fi
   fi
   ## Print exit code.
@@ -579,33 +586,33 @@ get_host_pkgs(){
   case "${os}" in
     Linux*)
       case "${distro}" in
-        "Debian"*|"Linux Mint"*|"LinuxMint"*|"mint"*|"Tails"*)
+        "Debian"*|"Tails"*)
           true "Debian"
-          pkg_mngr="apt"
-          pkg_mngr_install="${pkg_mngr} install --yes"
-          pkg_mngr_update="${pkg_mngr} update --yes"
-          pkg_mngr_check_installed="dpkg -s"
+          install_package_debian_common
           install_pkg netcat-openbsd
           install_virtualbox_debian
           install_signify signify-openbsd
           ;;
-        *"buntu"*)
-          true "Ubuntu"
-          pkg_mngr="apt"
-          pkg_mngr_install="${pkg_mngr} install --yes"
-          pkg_mngr_update="${pkg_mngr} update --yes"
-          pkg_mngr_check_installed="dpkg -s"
+        "Linux Mint"*|"LinuxMint"*|"mint"*)
+          true "Mint"
+          install_package_debian_common
           install_pkg netcat-openbsd
           install_virtualbox_ubuntu
           install_signify signify-openbsd
+          ;;
+        *"buntu"*)
+          true "Ubuntu"
           if [ "$(echo "${distro_version}" | tr -d ".")" -lt 2204 ]; then
             die 101 "Minimal ${distro} required version is 22.04, yours is ${distro_version}."
-          fi ;; "Kicksecure"|"Whonix")
+          fi
+          install_package_debian_common
+          install_pkg netcat-openbsd
+          install_virtualbox_ubuntu
+          install_signify signify-openbsd
+          ;;
+        "Kicksecure"|"Whonix")
           true "Kicksecure/Whonix"
-          pkg_mngr="apt"
-          pkg_mngr_install="${pkg_mngr} install --yes"
-          pkg_mngr_update="${pkg_mngr} update --yes"
-          pkg_mngr_check_installed="dpkg -s"
+          install_package_debian_common
           install_pkg netcat-openbsd
           install_virtualbox_kicksecure
           install_signify signify-openbsd
@@ -986,6 +993,14 @@ start_virtualbox(){
 }
 
 
+install_package_debian_common(){
+  pkg_mngr="apt-get"
+  pkg_mngr_install="${pkg_mngr} install --yes"
+  pkg_mngr_update="${pkg_mngr} update --yes"
+  pkg_mngr_check_installed="dpkg -s"
+}
+
+
 ## End installation of VirtualBox on Debian and derived systems.
 install_virtualbox_debian_common_end(){
   has vboxmanage || die 1 "Failed to locate 'vboxmanage' program."
@@ -998,15 +1013,15 @@ install_virtualbox_debian_common_end(){
 ## Install VirtualBox on Debian
 install_virtualbox_debian(){
   has vboxmanage && return 0
-  install_pkg apt-transport-https
-  install_pkg fasttrack-archive-keyring
-  test_pkg fasttrack-archive-keyring
   if grep -v "#" /etc/apt/sources.list /etc/apt/sources.list.d/*.list | \
     grep -e "://fasttrack.debian.net" \
     -e grep "://5phjdr2nmprmhdhw4fdqfxvpvt363jyoeppewju2oqllec7ymnolieyd.onion"
   then
     log info "Skipped adding fasttrack because it was already found."
   else
+    install_pkg apt-transport-https
+    install_pkg fasttrack-archive-keyring
+    test_pkg fasttrack-archive-keyring
     log info "Adding fasttrack repo to /etc/apt/sources.list.d/fasttrack.list"
     echo 'deb https://fasttrack.debian.net/debian/ bullseye-fasttrack main contrib non-free' | root_cmd tee /etc/apt/sources.list.d/fasttrack.list >/dev/null
   fi
@@ -1216,7 +1231,9 @@ set_trap(){
   case "${curr_shell}" in
     *bash|*ksh|*zsh)
       # shellcheck disable=SC2039
-      test "${curr_shell}" = "bash" && set -o errtrace
+      if test "${curr_shell}" = "bash"; then
+        set -o errtrace
+      fi
       # shellcheck disable=SC2039
       trap 'handle_exit $? ${LINENO:-}' ERR
       ;;
@@ -2183,14 +2200,12 @@ parse_opt(){
     ## is set to '~/', the parent '/home' is not writable.
 
     log info "Creating directory: '${directory_prefix}'."
-    if test "${dry_run}" != "1"; then
-      mkdir -p "${directory_prefix}" ||
-        die 1 "Failed to created directory: '${directory_prefix}'."
-      test -w "${directory_prefix}" ||
-        die 1 "Directory isn't writable: '${directory_prefix}'."
-      test -r "${directory_prefix}" ||
-        die 1 "Directory isn't readable: '${directory_prefix}'."
-    fi
+    mkdir -p "${directory_prefix}" ||
+      die 1 "Failed to created directory: '${directory_prefix}'."
+    test -w "${directory_prefix}" ||
+      die 1 "Directory isn't writable: '${directory_prefix}'."
+    test -r "${directory_prefix}" ||
+      die 1 "Directory isn't readable: '${directory_prefix}'."
 
     log_dir_main="${directory_prefix}/logs"
 
@@ -2205,13 +2220,11 @@ parse_opt(){
     fi
     log_file="${log_dir_cur}/log"
 
-    if test "${dry_run}" != "1"; then
-      ## If the commands below fail, it should have failed earlier for the
-      ## parent directory permissions, not below.
-      mkdir -p "${log_dir_cur}"
-      cp "${0}" "${log_dir_cur}"
-      touch "${log_file}"
-    fi
+    ## If the commands below fail, it should have failed earlier for the
+    ## parent directory permissions, not below.
+    mkdir -p "${log_dir_cur}"
+    cp "${0}" "${log_dir_cur}"
+    touch "${log_file}"
   fi
 
   # shellcheck disable=SC2194
@@ -2250,17 +2263,24 @@ log_term_and_file(){
   ## by sending it to /dev/null, while the desired method would be to avoid
   ## this workaround and simply be able to redirect with 2>/dev/null.
   ## Send f21/stdout to log file.
-  exec 1> "${log_file}"
+  exec 1>>"${log_file}"
   ## Send fd2/stderr to log file by default.
-  exec 2> "${log_file}"
-  ## If no show errors is set, send fd2/stderr to /dev/null.
+  exec 2>>"${log_file}"
+  ## If no_show_errors is set, send fd2/stderr to /dev/null.
   test "${no_show_errors}" = "1" && exec 2>/dev/null
   ## Send fd3 to the terminal
-  exec 3> "$(tty)"
-  ## Send output of log file to fd3 and send process to the background.
+  exec 3>>"$(tty)"
+  ## Bash has built-in feature to redirect xtrace to the specified file.
+  if test "${curr_shell}" = "bash"; then
+    # shellcheck disable=SC2039
+    exec 9>>"${log_file}.xtrace"
+    export BASH_XTRACEFD=9
+    set -o xtrace
+  fi
+  ## Copy output of log file to fd3 and send process to the background.
   tail -f "${log_file}" >&3 &
   ## Get background job PID.
-  tail_pid="$!"
+  tail_pid="${!}"
 }
 
 
