fix timeout of transfer Each program has different timeout options that work in different ways. Implement program specific timeouts when possible and resort to external core utils utility to ensure the maximum timeout is enforced.

diff --git a/usr/bin/installer-dist b/usr/bin/installer-dist
--- a/usr/bin/installer-dist
+++ b/usr/bin/installer-dist
@@ -620,6 +620,7 @@ get_independent_host_pkgs(){
     signify(){ signify-openbsd "${@}"; }
   fi
 
+  has timeout || die 1 "Timeout utility is missing."
   has curl || install_pkg curl
   test_pkg curl
   has rsync || install_pkg rsync
@@ -1011,14 +1012,29 @@ get_utilities(){
 
   ## curl|rsync
   transfer_utility=rsync
-  transfer_time_large_file="1800"
-  transfer_time_small_file="180"
+  ## 45m
+  transfer_max_time_large_file="2700"
+  ## 3m
+  transfer_max_time_small_file="180"
+  ## 10m
+  transfer_io_timeout="600"
+  ## 3m
+  transfer_connect_timeout="180"
   transfer_size_test_connection="200K"
   transfer_size_small_file="2K"
   transfer_size_large_file="3G"
   case ${transfer_utility} in
     curl)
-      transfer_time_opt="--max-time"
+      ## Maximum time in seconds that we allow the whole operation to take.
+      ## Option works but as rsync doesn't have it, we are using timeout
+      ## utility from coreutils.
+      #transfer_max_time_opt="--max-time"
+      ## Curl does not have I/O timeout.
+      transfer_io_timeout_opt=""
+      ## Maximum time in seconds that we allow curl's connection to take.
+      ## This only limits the connection phase, so if curl's connect in the
+      ## given period, it will continue.
+      transfer_connect_timeout_opt="--connect-timeout ${transfer_connect_timeout}"
       ## curl max-filesize is not a definitive barrier:
       ## NOTE:  The file size is not always known prior to download, and for
       ## such files this option has no effect even if the file transfer ends
@@ -1030,7 +1046,18 @@ get_utilities(){
       transfer_verbosity_opt=""
       ;;
     rsync*)
-      transfer_time_opt="--timeout"
+      ## Rsync does not have an option to set maximum time for of operation.
+      ## Option works but as rsync doesn't have it, we are using timeout
+      ## utility from coreutils.
+      #transfer_max_time_opt=""
+      ## If no data is transferred in the specified time, rsync will exit.
+      transfer_io_timeout_opt="--timeout ${transfer_io_timeout}"
+      ## Amount of time the client will wait for its connection to a server
+      ## to succeed.
+      ## Error when using this option:
+      ##   The --contimeout option may only be used when connecting to an
+      ##   rsync daemon.
+      #transfer_connect_timeout_opt="--contimeout ${transfer_connect_timeout}"
       transfer_size_opt="--max-size"
       transfer_dryrun_opt="--dry-run"
       transfer_output_dir_opt=""
@@ -1264,7 +1291,7 @@ get_version(){
   log info "API host: ${1}"
   cmd_raw_version="curl ${curl_transfer_proxy:-} $(get_proxy_cred version) \
       ${curl_opt_ssl:-} \
-      --max-time ${transfer_time_small_file} \
+      --max-time ${transfer_max_time_small_file} \
       --max-filesize ${transfer_size_small_file} \
       --url ${1}"
   if test "${dry_run}" = "1"; then
@@ -1299,14 +1326,19 @@ get_file(){
 
   case "${size}" in
     small)
-      download_opt="${transfer_time_opt} ${transfer_time_small_file} ${transfer_size_opt} ${transfer_size_small_file}"
+      download_opt_prefix="timeout ${transfer_max_time_small_file}"
+      download_opt="${transfer_size_opt} ${transfer_size_small_file}"
       ;;
     large)
-      download_opt="${transfer_time_opt} ${transfer_time_large_file} ${transfer_size_opt} ${transfer_size_large_file}"
+      download_opt_prefix="timeout ${transfer_max_time_large_file}"
+      download_opt="${transfer_size_opt} ${transfer_size_large_file}"
+      ;;
+    *)
+      log bug "Missing size option for get_file()."
       ;;
   esac
   # shellcheck disable=SC2046,SC2086
-  download_opt_full="${transfer_proxy_prefix:-} ${transfer_utility} ${transfer_verbosity_opt} ${transfer_proxy_suffix:-} $(get_proxy_cred ${round}) ${download_opt} ${transfer_output_file_opt} ${url} ${transfer_output_dir_opt} ${directory_prefix}"
+  download_opt_full="${download_opt_prefix} ${transfer_proxy_prefix:-} ${transfer_utility} ${transfer_verbosity_opt} ${transfer_proxy_suffix:-} $(get_proxy_cred ${round}) ${transfer_connect_timeout_opt:-} ${transfer_io_timeout_opt:-} ${download_opt} ${transfer_output_file_opt} ${url} ${transfer_output_dir_opt} ${directory_prefix}"
 
   log notice "Downloading ${url:-}."
   log_run "${download_opt_full}" || return 1
@@ -1717,9 +1749,9 @@ main(){
     if test "${dry_run}" != "1"; then
       log notice "Testing internet connection..."
       # shellcheck disable=SC2046,SC2086,SC2090
-      ${transfer_proxy_prefix:-} ${transfer_utility} \
+      timeout ${transfer_max_time_small_file} \
+        ${transfer_proxy_prefix:-} ${transfer_utility} \
         ${transfer_proxy_suffix:-} ${transfer_dryrun_opt} \
-        ${transfer_time_opt} ${transfer_time_small_file} \
         ${transfer_size_opt} ${transfer_size_test_connection} \
         ${url_origin} >/dev/null ||
         die $? "Can't connect to ${url_origin}, perhaps no internet?"
