improve output in case of errors

diff --git a/usr/bin/installer-dist b/usr/bin/installer-dist
--- a/usr/bin/installer-dist
+++ b/usr/bin/installer-dist
@@ -504,7 +504,7 @@ log(){
   case "${log_type}" in
     bug)
       #printf %s"${log_full:+$log_full }Please report this bug.\n" 1>&2
-      printf %s"${log_full} Please report this bug.\n" 1>&2
+      printf %s"${log_full}" 1>&2
       return 0
       ;;
     error)
@@ -597,16 +597,23 @@ handle_exit(){
   ## Exit without errors.
   test "${last_exit}" = "0" && end_exit
   ## Exit with errors.
-  log error "Current script: ${0}"
+  log notice "Current script: ${0}"
   # shellcheck disable=SC3028
   if test -n "${BASH_COMMAND:-}"; then
     # shellcheck disable=SC2039,3028,3054
-    log error "Function executed: ${FUNCNAME[1]}"
+    log notice "Function executed: ${FUNCNAME[1]}"
     # shellcheck disable=SC2039,3028,3054
-    log error "Command executed: ${BASH_COMMAND}"
+    log notice "Command executed: ${BASH_COMMAND}"
   fi
   ## some shells have a bug that displays line 1 as LINENO
   if test "${line_number}" -gt 2; then
+    log error "Error detected. Installer aborted."
+    log error "No panic. Nothing is broken. Just some rare condition has been hit."
+    log error "There is likely a solution for this problem."
+    log error "Try again. If this issue is transient (not happening again) it can be safely ignored."
+    log error "Please see ${guest_pretty} News and ${guest_pretty} User Help Forum."
+    log error "If not already reported, please report this bug!"
+    echo ""
     log bug "At line: ${line_number}."
     echo ""
     ## ideas from https://unix.stackexchange.com/questions/39623/trap-err-and-echoing-the-error-line
