output

diff --git a/usr/bin/installer-dist b/usr/bin/installer-dist
--- a/usr/bin/installer-dist
+++ b/usr/bin/installer-dist
@@ -1461,7 +1461,7 @@ install_signify(){
 ## Test if user accepts the license, if not, abort.
 check_license(){
   if [ "${non_interactive}" = "1" ]; then
-    log notice "License Check: User agreement confirmed via non_interactive setting."
+    log notice "License Check: 'success' - User agreement confirmed via non_interactive setting."
     return 0
   fi
 
@@ -1491,7 +1491,7 @@ check_license(){
         --no-label "Disagree" \
         --output-fd 1 \
         --yesno "${license}" 640 480 || return 1
-      log notice "${underline}License Check:${nounderline} User agreed with the license."
+      log notice "${underline}License Check:${nounderline} 'success' - User has accepted the license."
       ;;
     whiptail)
       ## When text is too long and scrolltext is needed, the yesno box
@@ -1503,18 +1503,18 @@ check_license(){
         --yes-button "Agree" \
         --no-button "Disagree" \
         --yesno "${license}" 24 80 || return 1
-      log notice "${underline}License Check:${nounderline} User agreed with the license."
+      log notice "${underline}License Check:${nounderline} 'success' - User has accepted the license."
       ;;
     *)
       printf '%s\n' "${license}"
-      printf '%s' "Do you agree with the license(s)? (yes/no): "
+      printf '%s' "Do you accept the license(s)? (yes/no): "
       read -r license_agreement
       case "${license_agreement}" in
         [yY][eE][sS])
-          log notice "${underline}License Check:${nounderline} User agreed with the license."
+          log notice "${underline}License Check:${nounderline} 'success' - User has accepted the license."
           ;;
         *)
-          log warn "${underline}License Check:${nounderline} User replied '${license_agreement}'"
+          log warn "${underline}License Check:${nounderline} 'FAIL' - User replied: '${license_agreement}'"
           return 1
           ;;
       esac
@@ -2427,7 +2427,7 @@ main(){
     log notice "If you wish to cancel installation, press Ctrl+C."
   fi
   ## The license function sleeps for some seconds to give time to abort
-  check_license || die 100 "User disagreed with the license."
+  check_license || die 100 "License Check: 'FAIL' - User declined the license."
 
   pre_check
 
