shellcheck fixes

diff --git a/usr/bin/installer-dist b/usr/bin/installer-dist
--- a/usr/bin/installer-dist
+++ b/usr/bin/installer-dist
@@ -20,7 +20,7 @@
 ##
 ## On Debian systems, the full text of the GNU General Public
 ## License version 3 can be found in the file
-## `/usr/share/common-licenses/GPL-3'.
+## '/usr/share/common-licenses/GPL-3'.
 ##
 ##########################
 ## BEGIN DEFAULT VALUES ##
@@ -78,15 +78,16 @@ all_args="${*}"
 start_time="$(date +%s)"
 
 ## colors
+# shellcheck disable=SC2034
 nocolor="\033[0m"
 bold="\033[1m"
 #nobold="\033[22m"
-underline="\033[4m"
-nounderline="\033[24m"
+#underline="\033[4m"
+#nounderline="\033[24m"
 red="\033[31m"
 green="\033[32m"
 yellow="\033[33m"
-blue="\033[34m"
+#blue="\033[34m"
 magenta="\033[35m"
 cyan="\033[36m"
 
@@ -121,11 +122,12 @@ not_as_root(){
 root_cmd(){
   test -z "${1:-}" && die 1 "Failed to pass arguments to root_cmd."
   if test "${dry_run}" = "1"; then
-    log info "Skipping running root command '${sucmd} ${@}' because dry_run is set"
+    log info "Skipping running root command '${sucmd} ${*}' because dry_run is set."
     return 0
   fi
   if test -n "${sucmd_quote:-}"; then
     true "sucmd_quote"
+    # shellcheck disable=SC2016
     ${sucmd} '${@}'
   else
     ${sucmd} "${@}"
@@ -275,7 +277,7 @@ set_arg(){
   if test -z "${arg_saved:-}"; then
     arg_saved="${1}=\"${2}\""
   else
-    if test -z "${var}"; then
+    if test -z "${var:-}"; then
       arg_saved="${arg_saved}\n${1}=\"${2}\""
     else
       arg_saved="${arg_saved}\n${1}=\"${2}\""
@@ -445,9 +447,10 @@ die(){
 log_and_run(){
   log info "Running command:\n$ ${1}"
   if test "${dry_run}" = "1"; then
-    true "Skipping running above logged command because dry_run is set"
+    true "Skipping running above logged command because dry_run is set."
     return 0
   fi
+  # shellcheck disable=SC2086
   exec ${1}
 }
 
@@ -547,9 +550,10 @@ get_host_pkgs(){
 
 
 install_pkg(){
-  pkgs="${@}"
+  pkgs="${*}"
   pkg_not_installed=""
   for pkg in ${pkgs}; do
+    # shellcheck disable=SC2086
     ${pkg_mngr_check_installed} "${pkg}" >/dev/null 2>&1 ||
       pkg_not_installed="${pkg_not_installed} ${pkg}"
   done
@@ -557,26 +561,28 @@ install_pkg(){
   if test -n "${pkg_not_installed}"; then
     if test "${dry_run}" = "1"; then
       log notice "Installing package(s):${pkg_not_installed}."
-      log info "Skipping installing packages because dry_run is set"
+      log info "Skipping installing packages because dry_run is set."
       return 0
     fi
     log notice "Updating package list."
+    # shellcheck disable=SC2086
     root_cmd ${pkg_mngr_update}
     log notice "Installing package(s):${pkg_not_installed}."
+    # shellcheck disable=SC2086
     root_cmd ${pkg_mngr_install} ${pkg_not_installed}
   fi
 }
 
 
 test_pkg(){
-  pkgs="${@}"
+  pkgs="${*}"
   pkg_not_installed=""
   for pkg in ${pkgs}; do
     ${pkg_mngr_check_installed} "${pkg}" >/dev/null 2>&1 ||
       pkg_not_installed="${pkg_not_installed} ${pkg}"
   done
 
-  if ! test -n ${pkg_not_installed}; then
+  if ! test -n "${pkg_not_installed}"; then
     die 1 "Failed to locate package(s):${pkg_not_installed}."
   fi
 }
@@ -611,7 +617,7 @@ install_virtualbox_debian(){
   else
     echo 'deb https://fasttrack.debian.net/debian/ bullseye-fasttrack main contrib non-free' | root_cmd tee /etc/apt/sources.list.d/fasttrack.list >/dev/null
   fi
-  install_pkg virtualbox linux-headers-$(dpkg --print-architecture)
+  install_pkg virtualbox "linux-headers-$(dpkg --print-architecture)"
   common_virtualbox_install_end
 }
 
@@ -625,7 +631,7 @@ install_virtualbox_ubuntu(){
 
 install_virtualbox_kicksecure(){
   has vboxmanage && return 0
-  install_pkg virtualbox linux-headers-$(dpkg --print-architecture)
+  install_pkg virtualbox "linux-headers-$(dpkg --print-architecture)"
   common_virtualbox_install_end
 }
 
@@ -734,13 +740,19 @@ set_trap(){
   curr_shell="$(ps | awk "/ $$ /" | awk '{print $4}')"
   ## sometimes the process name is the base name of the script with some
   ## missing letters.
-  if [ ${curr_shell}* = "${0##*/}" ]; then
-    shebang="$(head -1 $0)"
-    curr_shell="${shebang##*/}"
-  fi
+  case "${0##*/}" in
+    ${curr_shell}*)
+      ## necessary glob cause /bin/sh makes the file name
+      ## appear withone letter less
+      shebang="$(head -1 "${0}")"
+      curr_shell="${shebang##*/}"
+      ;;
+  esac
   case "${curr_shell}" in
     *bash|*ksh|*zsh)
+      # shellcheck disable=SC2039
       test "${curr_shell}" = "bash" && set -o errtrace
+      # shellcheck disable=SC2039
       trap 'handle_exit $? ${LINENO:-}' ERR
       ;;
   esac
@@ -756,9 +768,10 @@ get_system_stat(){
     return 1
   fi
 
+  ## https://www.whonix.org/wiki/RAM#Whonix_RAM_and_VRAM_Defaults
   ## min_ram_mb not used currently because less than total 4GB is too low
   ## already
-  ## https://www.whonix.org/wiki/RAM#Whonix_RAM_and_VRAM_Defaults
+  # shellcheck disable=SC2034
   case "${interface}" in
     xfce)
       min_ram_mb="3328"
@@ -777,7 +790,7 @@ get_system_stat(){
   fi
 
   free_space="$(df --output=avail -BG . | awk '/G$/{print substr($1, 1, length($1)-1)}')"
-  if [ ${free_space} -lt 10 ]; then
+  if [ "${free_space}" -lt 10 ]; then
     log error "You need at least 10G of available space, you only have ${free_space}G."
     return 1
   fi
@@ -792,15 +805,16 @@ pre_check(){
   set_trap
   get_os
   get_utilities
+  root_cmd echo hi
   ## below functions are difficult to emulate
   if ! get_system_stat && test "${dry_run}" = "1"; then
-    log info "Skipping failing commands because dry_run is set"
+    log info "Skipping failing get_system_stat() because dry_run is set."
   fi
   if ! get_virtualization && test "${dry_run}" = "1"; then
-    log info "Skipping failing commands because dry_run is set"
+    log info "Skipping failing get_virtualization() because dry_run is set."
   fi
   if test "${dry_run}" = "1"; then
-    log info "Skipping rest or pre_check() because dry_run is set"
+    log info "Skipping rest or pre_check() because dry_run is set."
     return 0
   fi
   get_host_pkgs
@@ -837,7 +851,7 @@ get_curl_proxy_cred(){
 check_tor_proxy(){
   log notice "Testing SOCKS proxy: ${proxy}."
   if test "${dry_run}" = "1"; then
-    log info "Faking SOCKS proxy response because dry_run is set"
+    log info "Faking SOCKS proxy response because dry_run is set."
     log notice "Connected to tor SOCKS proxy succesfully."
     return 0
   fi
@@ -900,6 +914,7 @@ get_version(){
   fi
   log info "Acquiring guest version from API."
   log info "API host: ${1}"
+  # shellcheck disable=SC2086,SC2046
   raw_version="$(curl ${curl_proxy:-} $(get_curl_proxy_cred) ${curl_opt_ssl:-} "${1}")"
   guest_version="$(printf '%s\n' "${raw_version}" | sed "s/<.*//")"
 }
@@ -1071,20 +1086,6 @@ get_virtualization(){
   verdict 0
 }
 
-## set default values of variables
-set_default(){
-  : "${arg_saved:=""}"
-  : "${guest:="whonix"}"
-  : "${hypervisor:="virtualbox"}"
-  : "${interface:="xfce"}"
-  : "${log_level:="notice"}"
-  : "${socks_proxy:=""}"
-  : "${onion:=""}"
-  : "${non_interactive:=""}"
-  : "${dry_run:=""}"
-  : "${dev:=""}"
-}
-
 #########################
 ## END SCRIPT SPECIFIC ##
 #########################
@@ -1092,34 +1093,6 @@ set_default(){
 ################
 ## BEGIN MAIN ##
 ################
-usage(){
-  printf %s"Usage: ${me} [options...]
- -g, --guest         Set guest. Options: kicksecure, whonix (default)
- -u, --guest-version <version>
-                     Set guest version, else query from API.
- -i, --interface <interface>
-                     Set interface. Options: cli, xfce (default)
- -m, --hypervisor <platform>
-                     Set virtualization. Options: kvm, virtualbox (default)
- -o, --onion         Download files over onion.
- -s, --socks-proxy <proxy>
-                     Set TCP SOCKS proxy for onion client connections.
-                       (default: TOR_SOCKS_HOST:TOR_SOCKS_PORT, if not set, try
-                       TBB proxy at 9150, else try system tor proxy at 9050)
- -l, --log-level <level>
-                     Set log level. Options: debug, info,
-                       notice (default), warn, error.
- -n, --non-interactive
-                     Set non-interactive mode, license will be accepted.
- -d, --dry-run       Fake run, log commands to info level without executing.
- -t, --getopt        Get parsed options and exit.
- -V, --version       Print script version.
- -h, --help          Print this help message.
-"
-  exit 1
-}
-
-
 main(){
   check_license || die 1 "User disagreed with the license."
   log notice "User agreed with the license."
@@ -1137,18 +1110,16 @@ main(){
   case "${guest}" in
     whonix)
       site_onion="dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion"
-      site="whonix.org"
-      site_dl="mirrors.dotsrc.org/${guest}"
+      site_clearnet="whonix.org"
+      site_download="mirrors.dotsrc.org/${guest}"
       ;;
     kicksecure)
       site_onion="w5j6stm77zs6652pgsij4awcjeel3eco7kvipheu6mtr623eyyehj4yd.onion"
-      site="kicksecure.com"
+      site_clearnet="kicksecure.com"
       #site_download="dotsrccccbidkzg7oc7oj4ugxrlfbt64qebyunxbrgqhxiwj3nl6vcad.onion/${guest}"
-      site_dl="dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion"
+      site_download="dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion"
       ;;
   esac
-  ##
-  site_mirror="mirrors.dotsrc.org/${guest}"
 
   guest_up="$(echo "${guest}" | awk '{$1=toupper(substr($1,0,1))substr($1,2)}1')"
 
@@ -1160,7 +1131,7 @@ main(){
       curl_opt_ssl=""
       url_origin="http://www.${site_onion}"
       url_download="http://download.${site_onion}"
-      #url_download="http://${site_dl}"
+      #url_download="http://${site_download}"
       url_version="w/index.php?title=Template:VersionNew&stable=0&action=raw"
       url_version="http://www.${site_onion}/${url_version}"
       ;;
@@ -1168,11 +1139,11 @@ main(){
       log info "Clearnet preferred."
       test -n "${socks_proxy}" && torify_conn
       curl_opt_ssl="--tlsv1.3 --proto =https"
-      url_origin="https://www.${site}"
-      url_download="https://${site_dl}"
-      #url_download="https://download.${site}"
+      url_origin="https://www.${site_clearnet}"
+      url_download="https://${site_download}"
+      #url_download="https://download.${site_clearnet}"
       url_version="w/index.php?title=Template:VersionNew&stable=0&action=raw"
-      url_version="https://www.${site}/${url_version}"
+      url_version="https://www.${site_clearnet}/${url_version}"
       ;;
   esac
 
@@ -1209,7 +1180,7 @@ main(){
       ;;
   esac
 
-  log_and_run "curl -sSf -m 20 --fail-early "${url_download}" >/dev/null" ||
+  log_and_run "curl -sSf -m 20 --fail-early ${url_download} >/dev/null" ||
     die 1 "Can't connect to destination, perhaps you don't have internet?"
 
   get_version "${url_origin}/${guest_version}."
@@ -1223,7 +1194,7 @@ main(){
   download_files "${curl_opt_save_dir}" || die 1 "Failed to download files."
 
   if test "${dry_run}" = "1"; then
-    log info "Ending run before doing integrity checks because dry_run is set"
+    log info "Ending run before doing integrity checks because dry_run is set."
     exit 0
   fi
 
@@ -1240,6 +1211,53 @@ main(){
   ${import_guest}
 
   log_elapsed_time
+}
+
+
+## set default values of variables
+set_default(){
+  : "${arg_saved:=""}"
+  : "${guest:="whonix"}"
+  : "${hypervisor:="virtualbox"}"
+  : "${interface:="xfce"}"
+  : "${log_level:="notice"}"
+  : "${socks_proxy:=""}"
+  : "${onion:=""}"
+  : "${non_interactive:=""}"
+  : "${dry_run:=""}"
+  : "${dev:=""}"
+}
+
+
+usage(){
+  printf %s"Usage: ${me} [options...]
+ -g, --guest         Set guest. Options: kicksecure, whonix (default)
+ -u, --guest-version <version>
+                     Set guest version, else query from API.
+ -i, --interface <interface>
+                     Set interface. Options: cli, xfce (default)
+ -m, --hypervisor <platform>
+                     Set virtualization. Options: kvm, virtualbox (default)
+ -o, --onion         Download files over onion.
+ -s, --socks-proxy <proxy>
+                     Set TCP SOCKS proxy for onion client connections.
+                       (default: TOR_SOCKS_HOST:TOR_SOCKS_PORT, if not set, try
+                       TBB proxy at 9150, else try system tor proxy at 9050)
+ -l, --log-level <level>
+                     Set log level. Options: debug, info,
+                       notice (default), warn, error.
+ -n, --non-interactive
+                     Set non-interactive mode, license will be accepted.
+ -d, --dry-run       Fake run, log commands to info level without executing.
+ -t, --getopt        Get parsed options and exit.
+ -V, --version       Print script version.
+ -h, --help          Print this help message.
+"
+  exit 1
+}
+
+parse_name(){
+  true 
 }
 
 
