refactoring

diff --git a/usr/bin/upgrade-nonroot b/usr/bin/upgrade-nonroot
--- a/usr/bin/upgrade-nonroot
+++ b/usr/bin/upgrade-nonroot
@@ -3,14 +3,35 @@
 ## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
 ## See the file COPYING for copying conditions.
 
-set -e
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
+
+if [ "$(id -u)" = "0" ]; then
+  ## Administrative ("root") rights already available.
+  ## No need to use a privilege escalation tool such as 'privleap' or 'sudo'.
+  exec /usr/bin/apt-get-update-plus dist-upgrade
+fi
+
+## This is never reached if running 'exec' above.
 
 # shellcheck source=../../../helper-scripts/usr/libexec/helper-scripts/use_leaprun.sh
 source /usr/libexec/helper-scripts/use_leaprun.sh
-
 if [ "${use_leaprun}" = 'yes' ]; then
   exec "${leaprun_exe}" upgrade-nonroot-wrapper
 fi
 
+# shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/package_installed_check.bsh
+source /usr/libexec/helper-scripts/package_installed_check.bsh
+if pkg_installed user-sysmaint-split ; then
+  kernel_cmdline="$(cat /proc/cmdline)"
+  if ! [[ "${kernel_cmdline}" =~ 'boot-role=sysmaint' ]]; then
+    1>&2 echo "$0: Cannot run \"apt-get-update-plus dist-upgrade\". Please reboot into \"PERSISTENT mode SYSMAINT\" to do this."
+    exit 1
+  fi
+fi
+
 ## This is never reached if running 'exec' above.
+
 exec sudo /usr/bin/apt-get-update-plus dist-upgrade
